/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set User Admin
         * @description Grant/revoke admin on a user (admin only). The first admin is still
         *     bootstrapped out of band via `make create-admin`.
         */
        patch: operations["set_user_admin_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Units */
        get: operations["list_units_api_v1_units_get"];
        put?: never;
        /** Create Unit */
        post: operations["create_unit_api_v1_units_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unit Facets */
        get: operations["unit_facets_api_v1_units_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units/{unit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Unit */
        get: operations["get_unit_api_v1_units__unit_id__get"];
        put?: never;
        post?: never;
        /** Delete Unit */
        delete: operations["delete_unit_api_v1_units__unit_id__delete"];
        options?: never;
        head?: never;
        /** Update Unit */
        patch: operations["update_unit_api_v1_units__unit_id__patch"];
        trace?: never;
    };
    "/api/v1/units/{unit_id}/weapons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Weapon */
        post: operations["link_weapon_api_v1_units__unit_id__weapons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units/{unit_id}/abilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Ability */
        post: operations["link_ability_api_v1_units__unit_id__abilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units/{unit_id}/weapons/{weapon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink Weapon */
        delete: operations["unlink_weapon_api_v1_units__unit_id__weapons__weapon_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units/{unit_id}/abilities/{ability_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink Ability */
        delete: operations["unlink_ability_api_v1_units__unit_id__abilities__ability_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Factions */
        get: operations["list_factions_api_v1_factions_get"];
        put?: never;
        /** Create Faction */
        post: operations["create_faction_api_v1_factions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subfactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Subfactions
         * @description Every created subfaction, optionally filtered to one faction.
         *
         *     Distinct from GET /taxonomy: that publishes the *allowed* subfaction names
         *     (from the constant); this lists the rows actually created in the DB (with ids).
         */
        get: operations["list_subfactions_api_v1_subfactions_get"];
        put?: never;
        /** Create Subfaction */
        post: operations["create_subfaction_api_v1_subfactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Faction Taxonomy
         * @description The allowed subfactions under each faction (for building dropdowns).
         *
         *     Sourced from the `FACTION_SUBFACTIONS` map, not the DB — these are the values
         *     `create_subfaction` will accept, whether or not any have been created yet.
         *
         *     Deliberately *not* under `/factions/...`: it's static reference data, not a
         *     faction resource, and `/factions/taxonomy` would collide with a future
         *     `GET /factions/{faction_id}` (both claim the same path slot). See ROADMAP R12.
         */
        get: operations["faction_taxonomy_api_v1_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subfactions/{subfaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Subfaction */
        delete: operations["delete_subfaction_api_v1_subfactions__subfaction_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weapons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Weapons */
        get: operations["list_weapons_api_v1_weapons_get"];
        put?: never;
        /** Create Weapon */
        post: operations["create_weapon_api_v1_weapons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weapons/{weapon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Weapon */
        delete: operations["delete_weapon_api_v1_weapons__weapon_id__delete"];
        options?: never;
        head?: never;
        /** Update Weapon */
        patch: operations["update_weapon_api_v1_weapons__weapon_id__patch"];
        trace?: never;
    };
    "/api/v1/abilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Abilities */
        get: operations["list_abilities_api_v1_abilities_get"];
        put?: never;
        /** Create Ability */
        post: operations["create_ability_api_v1_abilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/abilities/{ability_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Ability */
        delete: operations["delete_ability_api_v1_abilities__ability_id__delete"];
        options?: never;
        head?: never;
        /** Update Ability */
        patch: operations["update_ability_api_v1_abilities__ability_id__patch"];
        trace?: never;
    };
    "/api/v1/me/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inventory */
        get: operations["list_inventory_api_v1_me_inventory_get"];
        put?: never;
        /** Add Unit */
        post: operations["add_unit_api_v1_me_inventory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/inventory/{unit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Unit */
        delete: operations["remove_unit_api_v1_me_inventory__unit_id__delete"];
        options?: never;
        head?: never;
        /** Set Amount */
        patch: operations["set_amount_api_v1_me_inventory__unit_id__patch"];
        trace?: never;
    };
    "/api/v1/me/armies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Armies */
        get: operations["list_armies_api_v1_me_armies_get"];
        put?: never;
        /** Create Army */
        post: operations["create_army_api_v1_me_armies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/armies/{army_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Army */
        get: operations["get_army_api_v1_me_armies__army_id__get"];
        put?: never;
        post?: never;
        /** Delete Army */
        delete: operations["delete_army_api_v1_me_armies__army_id__delete"];
        options?: never;
        head?: never;
        /** Update Army */
        patch: operations["update_army_api_v1_me_armies__army_id__patch"];
        trace?: never;
    };
    "/api/v1/me/armies/{army_id}/shortfall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shortfall */
        get: operations["shortfall_api_v1_me_armies__army_id__shortfall_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/armies/{army_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate */
        get: operations["validate_api_v1_me_armies__army_id__validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/armies/{army_id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Unit */
        post: operations["add_unit_api_v1_me_armies__army_id__units_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/armies/{army_id}/units/{unit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Unit */
        delete: operations["remove_unit_api_v1_me_armies__army_id__units__unit_id__delete"];
        options?: never;
        head?: never;
        /** Set Amount */
        patch: operations["set_amount_api_v1_me_armies__army_id__units__unit_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbilityLink */
        AbilityLink: {
            /**
             * Ability Id
             * Format: uuid
             */
            ability_id: string;
        };
        /** Ability_Create */
        Ability_Create: {
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** Ability_Read */
        Ability_Read: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** Ability_Update */
        Ability_Update: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** AdminUpdate */
        AdminUpdate: {
            /** Is Admin */
            is_admin: boolean;
        };
        /** AmountSet */
        AmountSet: {
            /** Amount */
            amount: number;
        };
        /** ArmyUnitAdd */
        ArmyUnitAdd: {
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
            /**
             * Amount
             * @default 1
             */
            amount: number;
        };
        /** ArmyUnit_Read */
        ArmyUnit_Read: {
            unit: components["schemas"]["Unit_Read"];
            /** Amount */
            amount: number;
        };
        /** Army_Create */
        Army_Create: {
            /** Name */
            name: string;
            /**
             * Faction Id
             * Format: uuid
             */
            faction_id: string;
            /** Subfaction Id */
            subfaction_id?: string | null;
            /** Description */
            description?: string | null;
            /** Points Limit */
            points_limit?: number | null;
        };
        /** Army_Read */
        Army_Read: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Faction Id
             * Format: uuid
             */
            faction_id: string;
            /** Subfaction Id */
            subfaction_id: string | null;
            /** Description */
            description: string | null;
            /** Points Limit */
            points_limit: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Points Total
             * @default 0
             */
            points_total: number;
            /**
             * Units
             * @default []
             */
            units: components["schemas"]["ArmyUnit_Read"][];
        };
        /** Army_Update */
        Army_Update: {
            /** Name */
            name?: string | null;
            /** Faction Id */
            faction_id?: string | null;
            /** Subfaction Id */
            subfaction_id?: string | null;
            /** Description */
            description?: string | null;
            /** Points Limit */
            points_limit?: number | null;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * FactionName
         * @description The canonical top-level Warhammer 40k factions (grand alliances).
         *
         *     A faction is the broad grouping; the specific army (Tyranids, Necrons,
         *     Death Guard, …) is a `Subfaction` beneath it — e.g. faction ``Xenos`` →
         *     subfaction ``Tyranids``. This set is fixed and known, so faction creation is
         *     restricted to these values: a misspelling is simply not a member and is
         *     rejected rather than creating a junk row. No migration is needed to change
         *     it (the DB column stays a plain string).
         * @enum {string}
         */
        FactionName: "Imperium" | "Xenos" | "Chaos" | "Space Marines";
        /** Faction_Create */
        Faction_Create: {
            name: components["schemas"]["FactionName"];
        };
        /** Faction_Read */
        Faction_Read: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Subfactions
             * @default []
             */
            subfactions: components["schemas"]["Subfaction_Read"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InventoryAdd */
        InventoryAdd: {
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
            /**
             * Amount
             * @default 1
             */
            amount: number;
        };
        /** Page[Ability_Read] */
        Page_Ability_Read_: {
            /** Items */
            items: components["schemas"]["Ability_Read"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Army_Read] */
        Page_Army_Read_: {
            /** Items */
            items: components["schemas"]["Army_Read"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Faction_Read] */
        Page_Faction_Read_: {
            /** Items */
            items: components["schemas"]["Faction_Read"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Subfaction_ListRead] */
        Page_Subfaction_ListRead_: {
            /** Items */
            items: components["schemas"]["Subfaction_ListRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Unit_Read] */
        Page_Unit_Read_: {
            /** Items */
            items: components["schemas"]["Unit_Read"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[UserUnit_Read] */
        Page_UserUnit_Read_: {
            /** Items */
            items: components["schemas"]["UserUnit_Read"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Weapon_Read] */
        Page_Weapon_Read_: {
            /** Items */
            items: components["schemas"]["Weapon_Read"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Register_Create */
        Register_Create: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Shortfall_Read */
        Shortfall_Read: {
            unit: components["schemas"]["Unit_Read"];
            /** In List */
            in_list: number;
            /** Owned */
            owned: number;
            /** Need */
            need: number;
        };
        /** Subfaction_Create */
        Subfaction_Create: {
            /**
             * Faction Id
             * Format: uuid
             */
            faction_id: string;
            /** Name */
            name: string;
        };
        /** Subfaction_ListRead */
        Subfaction_ListRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Faction Id
             * Format: uuid
             */
            faction_id: string;
            /** Name */
            name: string;
        };
        /** Subfaction_Read */
        Subfaction_Read: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UnitFacets */
        UnitFacets: {
            /** Total */
            total: number;
            /** By Faction */
            by_faction: {
                [key: string]: number;
            };
        };
        /** Unit_Create */
        Unit_Create: {
            /**
             * Faction Id
             * Format: uuid
             */
            faction_id: string;
            /** Unit Name */
            unit_name: string;
            /** Movement */
            movement: number;
            /** Toughness */
            toughness: number;
            /** Armor Save */
            armor_save: number;
            /** Wounds */
            wounds: number;
            /** Leadership */
            leadership: number;
            /** Objective Control */
            objective_control: number;
            /** Points */
            points: number;
            /** Invulnerable Save */
            invulnerable_save?: number | null;
            /** Subfaction Id */
            subfaction_id?: string | null;
            /** Keywords */
            keywords?: string[] | null;
        };
        /** Unit_Read */
        Unit_Read: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Unit Name */
            unit_name: string;
            /**
             * Faction Id
             * Format: uuid
             */
            faction_id: string;
            /** Subfaction Id */
            subfaction_id: string | null;
            /** Movement */
            movement: number;
            /** Toughness */
            toughness: number;
            /** Armor Save */
            armor_save: number;
            /** Wounds */
            wounds: number;
            /** Invulnerable Save */
            invulnerable_save: number | null;
            /** Leadership */
            leadership: number;
            /** Objective Control */
            objective_control: number;
            /** Points */
            points: number;
            /** Keywords */
            keywords: string[];
            /**
             * Weapons
             * @default []
             */
            weapons: components["schemas"]["Weapon_Read"][];
            /**
             * Abilities
             * @default []
             */
            abilities: components["schemas"]["Ability_Read"][];
        };
        /** Unit_Update */
        Unit_Update: {
            /** Unit Name */
            unit_name?: string | null;
            /** Faction Id */
            faction_id?: string | null;
            /** Subfaction Id */
            subfaction_id?: string | null;
            /** Movement */
            movement?: number | null;
            /** Toughness */
            toughness?: number | null;
            /** Armor Save */
            armor_save?: number | null;
            /** Wounds */
            wounds?: number | null;
            /** Invulnerable Save */
            invulnerable_save?: number | null;
            /** Leadership */
            leadership?: number | null;
            /** Objective Control */
            objective_control?: number | null;
            /** Points */
            points?: number | null;
            /** Keywords */
            keywords?: string[] | null;
        };
        /** UserUnit_Read */
        UserUnit_Read: {
            unit: components["schemas"]["Unit_Read"];
            /** Amount */
            amount: number;
        };
        /** User_Read */
        User_Read: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue_Read */
        ValidationIssue_Read: {
            /** Kind */
            kind: string;
            /** Detail */
            detail: string;
            unit?: components["schemas"]["Unit_Read"] | null;
        };
        /** Validation_Read */
        Validation_Read: {
            /** Ok */
            ok: boolean;
            /** Points Total */
            points_total: number;
            /** Points Limit */
            points_limit: number | null;
            /** Issues */
            issues: components["schemas"]["ValidationIssue_Read"][];
        };
        /** WeaponLink */
        WeaponLink: {
            /**
             * Weapon Id
             * Format: uuid
             */
            weapon_id: string;
        };
        /** Weapon_Create */
        Weapon_Create: {
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Attacks */
            attacks: string;
            /** Weapon Skill */
            weapon_skill: number;
            /** Strength */
            strength: number;
            /** Armor Piercing */
            armor_piercing: number;
            /** Damage */
            damage: string;
            /** Range Inches */
            range_inches?: number | null;
            /** Keywords */
            keywords?: string[] | null;
        };
        /** Weapon_Read */
        Weapon_Read: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Keywords */
            keywords: string[];
            /** Range Inches */
            range_inches: number | null;
            /** Attacks */
            attacks: string;
            /** Weapon Skill */
            weapon_skill: number;
            /** Strength */
            strength: number;
            /** Armor Piercing */
            armor_piercing: number;
            /** Damage */
            damage: string;
        };
        /** Weapon_Update */
        Weapon_Update: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Attacks */
            attacks?: string | null;
            /** Weapon Skill */
            weapon_skill?: number | null;
            /** Strength */
            strength?: number | null;
            /** Armor Piercing */
            armor_piercing?: number | null;
            /** Damage */
            damage?: string | null;
            /** Range Inches */
            range_inches?: number | null;
            /** Keywords */
            keywords?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register_Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User_Read"];
                };
            };
        };
    };
    set_user_admin_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_units_api_v1_units_get: {
        parameters: {
            query?: {
                faction_id?: string | null;
                subfaction_id?: string | null;
                /** @description case-insensitive name search */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Unit_Read_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_unit_api_v1_units_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Unit_Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unit_facets_api_v1_units_facets_get: {
        parameters: {
            query?: {
                subfaction_id?: string | null;
                /** @description case-insensitive name search */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitFacets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unit_api_v1_units__unit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_unit_api_v1_units__unit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_unit_api_v1_units__unit_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Unit_Update"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_weapon_api_v1_units__unit_id__weapons_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeaponLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_ability_api_v1_units__unit_id__abilities_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbilityLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlink_weapon_api_v1_units__unit_id__weapons__weapon_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
                weapon_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlink_ability_api_v1_units__unit_id__abilities__ability_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
                ability_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_factions_api_v1_factions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Faction_Read_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_faction_api_v1_factions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Faction_Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faction_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subfactions_api_v1_subfactions_get: {
        parameters: {
            query?: {
                faction_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Subfaction_ListRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subfaction_api_v1_subfactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Subfaction_Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subfaction_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    faction_taxonomy_api_v1_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    delete_subfaction_api_v1_subfactions__subfaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subfaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_weapons_api_v1_weapons_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Weapon_Read_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_weapon_api_v1_weapons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Weapon_Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Weapon_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_weapon_api_v1_weapons__weapon_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weapon_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_weapon_api_v1_weapons__weapon_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                weapon_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Weapon_Update"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Weapon_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_abilities_api_v1_abilities_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Ability_Read_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ability_api_v1_abilities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ability_Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ability_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ability_api_v1_abilities__ability_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ability_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ability_api_v1_abilities__ability_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ability_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ability_Update"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ability_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inventory_api_v1_me_inventory_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserUnit_Read_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_unit_api_v1_me_inventory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserUnit_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_unit_api_v1_me_inventory__unit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_amount_api_v1_me_inventory__unit_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmountSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserUnit_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_armies_api_v1_me_armies_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Army_Read_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_army_api_v1_me_armies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Army_Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Army_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_army_api_v1_me_armies__army_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                army_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Army_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_army_api_v1_me_armies__army_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                army_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_army_api_v1_me_armies__army_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                army_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Army_Update"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Army_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shortfall_api_v1_me_armies__army_id__shortfall_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                army_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shortfall_Read"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_api_v1_me_armies__army_id__validate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                army_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Validation_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_unit_api_v1_me_armies__army_id__units_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                army_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArmyUnitAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArmyUnit_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_unit_api_v1_me_armies__army_id__units__unit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
                army_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_amount_api_v1_me_armies__army_id__units__unit_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
                army_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmountSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArmyUnit_Read"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
