/* GENERATED by scripts/gen-api.mjs -- do not edit by hand.
 *
 * Runtime schemas for every response shape the API can return, generated from the
 * same openapi.json as schema.d.ts so the two cannot disagree (ROADMAP F11).
 * Run 'npm run gen:api'; CI fails if this file drifts from the backend.
 */

import { z } from 'zod'

export const User_Read = z.object({
    "id": z.string(),
    "username": z.string(),
    "email": z.string(),
    "is_admin": z.boolean(),
  })

export const ValidationError = z.object({
    "loc": z.array(z.union([z.string(), z.number()])),
    "msg": z.string(),
    "type": z.string(),
  })

export const HTTPValidationError = z.object({
    "detail": z.array(ValidationError).optional(),
  })

export const Token = z.object({
    "access_token": z.string(),
    "token_type": z.string(),
  })

export const Weapon_Read = z.object({
    "id": z.string(),
    "name": z.string(),
    "category": z.string(),
    "keywords": z.array(z.string()),
    "range_inches": z.number().nullable(),
    "attacks": z.string(),
    "weapon_skill": z.number(),
    "strength": z.number(),
    "armor_piercing": z.number(),
    "damage": z.string(),
  })

export const Ability_Read = z.object({
    "id": z.string(),
    "name": z.string(),
    "description": z.string(),
  })

export const Unit_Read = z.object({
    "id": z.string(),
    "unit_name": z.string(),
    "faction_id": z.string(),
    "subfaction_id": z.string().nullable(),
    "movement": z.number(),
    "toughness": z.number(),
    "armor_save": z.number(),
    "wounds": z.number(),
    "invulnerable_save": z.number().nullable(),
    "leadership": z.number(),
    "objective_control": z.number(),
    "points": z.number(),
    "keywords": z.array(z.string()),
    "weapons": z.array(Weapon_Read),
    "abilities": z.array(Ability_Read),
  })

export const Page_Unit_Read_ = z.object({
    "items": z.array(Unit_Read),
    "total": z.number(),
    "limit": z.number(),
    "offset": z.number(),
  })

export const UnitFacets = z.object({
    "total": z.number(),
    "by_faction": z.record(z.string(), z.number()),
  })

export const Subfaction_Read = z.object({
    "id": z.string(),
    "name": z.string(),
  })

export const Faction_Read = z.object({
    "id": z.string(),
    "name": z.string(),
    "subfactions": z.array(Subfaction_Read),
  })

export const Page_Faction_Read_ = z.object({
    "items": z.array(Faction_Read),
    "total": z.number(),
    "limit": z.number(),
    "offset": z.number(),
  })

export const Subfaction_ListRead = z.object({
    "id": z.string(),
    "faction_id": z.string(),
    "name": z.string(),
  })

export const Page_Subfaction_ListRead_ = z.object({
    "items": z.array(Subfaction_ListRead),
    "total": z.number(),
    "limit": z.number(),
    "offset": z.number(),
  })

export const Page_Weapon_Read_ = z.object({
    "items": z.array(Weapon_Read),
    "total": z.number(),
    "limit": z.number(),
    "offset": z.number(),
  })

export const Page_Ability_Read_ = z.object({
    "items": z.array(Ability_Read),
    "total": z.number(),
    "limit": z.number(),
    "offset": z.number(),
  })

export const UserUnit_Read = z.object({
    "unit": Unit_Read,
    "amount": z.number(),
  })

export const Page_UserUnit_Read_ = z.object({
    "items": z.array(UserUnit_Read),
    "total": z.number(),
    "limit": z.number(),
    "offset": z.number(),
  })

export const ArmyUnit_Read = z.object({
    "unit": Unit_Read,
    "amount": z.number(),
  })

export const Army_Read = z.object({
    "id": z.string(),
    "name": z.string(),
    "faction_id": z.string(),
    "subfaction_id": z.string().nullable(),
    "description": z.string().nullable(),
    "points_limit": z.number().nullable(),
    "created_at": z.string(),
    "points_total": z.number(),
    "units": z.array(ArmyUnit_Read),
  })

export const Page_Army_Read_ = z.object({
    "items": z.array(Army_Read),
    "total": z.number(),
    "limit": z.number(),
    "offset": z.number(),
  })

export const Shortfall_Read = z.object({
    "unit": Unit_Read,
    "in_list": z.number(),
    "owned": z.number(),
    "need": z.number(),
  })

export const ValidationIssue_Read = z.object({
    "kind": z.string(),
    "detail": z.string(),
    "unit": Unit_Read.nullable().optional(),
  })

export const Validation_Read = z.object({
    "ok": z.boolean(),
    "points_total": z.number(),
    "points_limit": z.number().nullable(),
    "issues": z.array(ValidationIssue_Read),
  })
